[package]
name = "run-pipeline"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.20.2"
serde = "1.0.219"
serde_yaml = "0.9.34"

[dev-dependencies]
assertor = "0.0.3"
fastrand = "2.3.0"
